export default {
  $: '',
  '$.swagger': '',
  '$.info': '',
  '$.info.contact': '',
  '$.tags.#': '',
  '$.tags.#.externalDocs': '',
  '$.schemes.#': '',
  '$.paths': '',
  '$.paths.$aPath': '',
  '$.paths.$aPath.$aVerb': '',
  '$.paths.$aPath.$aVerb.tags.#': '',
  '$.paths.$aPath.$aVerb.consumes.#': '',
  '$.paths.$aPath.$aVerb.produces.#': '',
  '$.paths.$aPath.$aVerb.parameters.#': '',
  '$.paths.$aPath.$aVerb.parameters.#.items':
    'It is used when type = array, Specifies array elem model',
  '$.paths.$aPath.$aVerb.parameters.#.items.enum.#': '',
  '$.paths.$aPath.$aVerb.parameters.#.schema':
    'Used for specify parameter model',
  '$.paths.$aPath.$aVerb.parameters.#.schema.$ref':
    'Useful if you want to refer a Model in place of specify it again. It is written $ref literally',
  '$.paths.$aPath.$aVerb.responses': '',
  '$.paths.$aPath.$aVerb.responses.$aRespCode': '',
  '$.paths.$aPath.$aVerb.responses.$aRespCode.schema': '',
  '$.paths.$aPath.$aVerb.responses.$aRespCode.headers': '',
  '$.paths.$aPath.$aVerb.responses.$aRespCode.headers.$aHeaderName': '',
  '$.paths.$aPath.$aVerb.security.#': '',
  '$.paths.$aPath.$aVerb.security.#.$aSecurityDef.#': '',
  '$.securityDefinitions': '',
  '$.securityDefinitions.$aSecurityDef': '',
  '$.securityDefinitions.$aSecurityDef.scopes': '',
  '$.securityDefinitions.api_key': '',
  '$.definitions': '',
  '$.definitions.$aDef': '',
  '$.definitions.$aDef.properties': '',
  '$.definitions.$aDef.properties.$aProp': '',
  '$.definitions.$aDef.xml': '',
  '$.externalDocs': '',
};
