swagger: '2.0'
info:
  version: '1'
paths:
  /actualPath/to/my/resource:
    get:
      tags: []
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/cat'
      - in: query
        type: integer
        format: int64
definitions:
  cat:
    properties:
      id:
        type: integer
        format: int64
        pattern: '^\d{3}-\d{2}-\d{4}$'
