swagger: '2.0'
info:
  version: '1'
paths:
  /actualPath/to/my/resource:
    get:
      tags: []
      parameters:
      - in: body
        name: body
        schema:
          $ref: '#/definitions/cat'
      - in: query
        type: integer
        format: int64
securityDefinitions:
  OAuth2:
    type: oauth2
    flow: accessCode
    authorizationUrl: 'https://example.com/oauth/authorize'
    tokenUrl: 'https://example.com/oauth/token'
    scopes:
      read: Grants read access
      write: Grants write access
      admin: Grants read and write access to administrative information
definitions:
  cat:
    properties:
      id:
        type: integer
        format: int64
        pattern: '^\d{3}-\d{2}-\d{4}$'
